on: workflow_dispatch
name: Release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: enonicpublisher
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build and push
        run: ./create_and_push_images.sh
