on: workflow_dispatch
name: Release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:qemu-v6.2.0
          platforms: arm64,amd64

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build and push
        run: create_and_push_images.sh
